export default {
  "login": "mechiragjain",
  "id": 20258004,
  "node_id": "MDQ6VXNlcjIwMjU4MDA0",
  "avatar_url": "https://avatars.githubusercontent.com/u/20258004?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/mechiragjain",
  "html_url": "https://github.com/mechiragjain",
  "followers_url": "https://api.github.com/users/mechiragjain/followers",
  "following_url": "https://api.github.com/users/mechiragjain/following{/other_user}",
  "gists_url": "https://api.github.com/users/mechiragjain/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/mechiragjain/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/mechiragjain/subscriptions",
  "organizations_url": "https://api.github.com/users/mechiragjain/orgs",
  "repos_url": "https://api.github.com/users/mechiragjain/repos",
  "events_url": "https://api.github.com/users/mechiragjain/events{/privacy}",
  "received_events_url": "https://api.github.com/users/mechiragjain/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Chirag Jain",
  "company": "Hungama Deal",
  "blog": "https://chiragjain.co.in",
  "location": "Jaipur",
  "email": null,
  "hireable": null,
  "bio": "Founder at Hungama Deal 🛍 & Dev Meet 🎓 | Web Developer 👨🏻‍💻 | Marketing Specialist | Student Partner @microsoft",
  "twitter_username": null,
  "public_repos": 16,
  "public_gists": 0,
  "followers": 22,
  "following": 3,
  "created_at": "2016-07-02T16:08:37Z",
  "updated_at": "2021-04-07T14:50:08Z"
};
